name: CI

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch: {}

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint shell scripts
        run: |
          if ls scripts/*.sh >/dev/null 2>&1; then
            shellcheck scripts/*.sh
          else
            echo "No shell scripts to lint."
          fi

  python_lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Ruff lint
        run: |
          pip install ruff
          ruff check || true
